image: qasico/go:latest

before_script:
  - go version
  - mkdir $GOPATH/src/git.qasico.com
  - mkdir $GOPATH/src/git.qasico.com/cuxs
  - WD="$GOPATH/src/git.qasico.com/cuxs/env"

test:
  script:
    - "cp -R $(pwd) $WD && cd $WD"
    - gotest
