image: qasico/go:latest

services:
  - mongo:latest

before_script:
  - go version
  - mkdir $GOPATH/src/git.qasico.com
  - mkdir $GOPATH/src/git.qasico.com/cuxs
  - WD="$GOPATH/src/git.qasico.com/cuxs/version"

variables:
  MGO_HOST: mongo
  MGO_DB: version
  MGO_DOCV_COLLECTION: docv_document

test:
  script:
    - "cp -R $(pwd) $WD && cd $WD"
    - glide install
    - gotest